---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```

## Load in the FAS Litters data

```{r}
litters_df = read_csv('./data/FAS_litters.csv')
litters_df = janitor:: clean_names(litters_df)
```

```{r}
litters_df
```


## 'Select'

Choose some columns and not others.

```{r}
select(litters_df, group, gd0_weight)
select(litters_df, group, gd0_weight:gd_of_birth)
select(litters_df, -litter_number)
```





Renaming columns
```{r}
select(litters_df, GROUP = group, LITTer_NUMBER = litter_number)
```
```{r} 
rename(litters_df, GGRROUP = group)  #same as before
```

use ?select_helpers


```{r}
select(litters_df, starts_with('gd'))
```


```{r}
select(litters_df, litter_number, everything())
```


```{r}
relocate(litters_df, litter_number)  #same as before
```




## 'filter'

```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth ==20))
```
```{r}
filter(litters_df, gd_of_birth != 20)  #same as before
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```
```{r}
filter(litters_df, group == 'Mod8')
```

```{r}
filter(litters_df, group %in% c('Con7', 'Mod8'))
```




## 'mutate'

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)
```
```{r}
mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))
```

## 'arrange'

```{r}
arrange(litters_df, pups_born_alive)
```

```{r}
arrange(litters_df, pups_born_alive, gd0_weight)
```




## '%>%' and then  (shift command m)

```{r}
litters_data_raw = read_csv('./data/FAS_litters.csv')
litters_clean_name = janitor:: clean_names(litters_data_raw)
litters_data_selected = select(litters_clean_name, -pups_survive)
litters_mutated = mutate(litters_data_selected, wt_gain = gd18_weight - gd0_weight)
litters_without_missing = drop_na(litters_mutated, gd0_weight)

```

Use the pipe operator instead

```{r}
litters_df = 
  read_csv('./data/FAS_litters.csv') %>% 
  janitor:: clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(wt_gain = gd18_weight - gd0_weight) %>% 
  drop_na(gd0_weight)
```



























